// The user-facing features that MUST have in-app help (coverage gate). Adding a
// feature here requires a topic with the matching featureKey (see
// __tests__/help/coverage.test.ts).
export const FEATURES = [
  { key: "generation", label: "Generating a book" },
  { key: "reading", label: "Reading a book" },
  { key: "provider-keys", label: "Provider API keys (BYOK)" },
  { key: "diagrams", label: "Diagrams" },
  { key: "export", label: "Export (EPUB3 / PDF)" },
  { key: "sharing", label: "Draft sharing" },
  { key: "accounts", label: "Accounts & sign-in" },
  { key: "plans", label: "Plans & billing" },
  { key: "figures", label: "Figures (attached images)" },
  { key: "reviews", label: "Reviewing & approving projects" },
  { key: "projects", label: "Creating & managing projects" },
  { key: "make-a-post", label: "Make a post" },
  { key: "publish-card", label: "Publish an image card" },
  { key: "publish-carousel", label: "Publish a carousel" },
  { key: "publish-animated", label: "Publish an animated card" },
  { key: "publish-audio", label: "Publish narrated audio" },
  { key: "appearance", label: "Appearance & themes" },
  { key: "sources", label: "Sources (Capture)" },
  { key: "draft-viewer", label: "Reading, editing & regenerating a draft" },
  { key: "generate-full-book", label: "Generate full book" },
  { key: "project-fields", label: "New Project fields (Title, Topic, Audience, Goal)" },
  { key: "word-export", label: "Word (.docx) export" },
  { key: "kdp-export", label: "Export for Kindle (KDP)" },
  { key: "publish-pack", label: "Download a publish pack for retailers" },
  { key: "epub2-export", label: "EPUB 2 export (max compatibility)" },
  { key: "grounding-report", label: "Quality report (coverage, readability & grounding)" },
  { key: "originality-report", label: "Originality check (source overlap)" },
  { key: "project-rights", label: "Rights & attribution (copyright)" },
  { key: "project-structure", label: "Building a project's outline (Structure)" },
  { key: "project-drafts", label: "Generating project drafts (Drafts)" },
  { key: "project-publish", label: "Publishing a project's validated work" },
  { key: "reader-audio", label: "Listening to a book's narration" },
  { key: "narrate-topic", label: "Generating narration for a topic" },
  { key: "backup-restore", label: "Backup & restore your library" },
] as const;

export type FeatureKey = (typeof FEATURES)[number]["key"];
