import type { HelpTopic } from "@/help";
import { providerKeyDefs } from "./providerDefs";

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: "getting-started",
    title: "Getting started",
    keywords: ["start", "begin", "first", "setup", "onboard", "books", "library"],
    blocks: [
      {
        kind: "text",
        text: "Mentible turns what you want to learn into a real, readable book, generated by an AI model you connect. Two finished books are already in your Library — open them right now, no account or key needed. When you're ready to make your own, here's the path:",
      },
      {
        kind: "steps",
        steps: [
          "Optional: sign in to sync your library across devices — or keep reading without an account.",
          "Add a provider API key in Settings. Claude (Anthropic) is recommended for finished books; free tiers exist if you just want to try it. Your key stays on your device.",
          "In Books, start a New Book and structure its table of contents.",
          "Generate — each topic is written with math, diagrams and tables, scoped by level and depth.",
          "Save the finished book to your Library to read or export.",
        ],
      },
      { kind: "action", label: "Create your account", step: "signup" },
      { kind: "action", label: "Add an API key", step: "key" },
    ],
  },
  {
    id: "getting-started-account",
    title: "Create your account & sign in",
    featureKey: "accounts",
    keywords: [
      "account", "sign in", "signin", "sign up", "signup", "login", "log in",
      "register", "google", "email", "password", "confirm", "verify", "sync",
    ],
    blocks: [
      {
        kind: "text",
        text: "An account is optional but recommended: it syncs your library and provider settings across your devices. You can sign up with an email and password, or continue with Google. You can always read the included books and use a BYOK key without an account.",
      },
      {
        kind: "steps",
        steps: [
          "Open the sign-in screen (or the first-run wizard) and choose Create account.",
          "Enter your email and a password (at least 6 characters), or tap Continue with Google.",
          "If you signed up with email, check your inbox and tap the confirmation link, then sign in.",
          "Once signed in, your library and provider settings sync automatically.",
        ],
      },
      { kind: "action", label: "Start the sign-up walkthrough", step: "signup" },
      {
        kind: "defs",
        defs: [
          {
            term: "Didn't get the confirmation email",
            def: "Check your spam folder and that the address is correct. Re-running sign-up resends the link.",
          },
          {
            term: "“Continue with Google” did nothing",
            def: "The sign-in browser was likely dismissed. Tap Continue with Google again and complete the Google prompt.",
          },
          {
            term: "Sign-in isn't available",
            def: "Some builds (including the demo) run without accounts — you can still read the included books and use a BYOK key without signing in.",
          },
        ],
      },
      { kind: "link", label: "Open sign-in →", href: "/sign-in" },
    ],
  },
  {
    id: "provider-keys",
    title: "Choose a provider & get an API key",
    featureKey: "provider-keys",
    keywords: [
      "key", "api", "byok", "provider", "anthropic", "claude", "openai", "groq",
      "openrouter", "gemini", "google", "free", "paid", "billing", "cost",
    ],
    blocks: [
      {
        kind: "text",
        text: "Mentible is bring-your-own-key (BYOK): you connect your own LLM account and are billed by that provider directly. Your key is stored in your device's secure storage and sent per request — never logged or stored on a server. You can add more than one provider and switch between them in Settings.",
      },
      {
        kind: "text",
        text: "Want to try it free? Groq, Google Gemini and OpenRouter all have free tiers (output is draft-grade). Anthropic (Claude) gives the best quality for finished books but is paid.",
      },
      { kind: "defs", defs: providerKeyDefs() },
      {
        kind: "steps",
        steps: [
          "In Settings (or the first-run wizard), pick a provider.",
          "Open that provider's console using the link and create an API key.",
          "Copy the key and paste it into the key field — it's checked for the right shape and saved on your device.",
          "Your key is verified the first time you generate; if it's wrong you'll see a clear error.",
        ],
      },
      { kind: "action", label: "Start the API-key walkthrough", step: "key" },
      { kind: "link", label: "Open Settings →", href: "/settings" },
    ],
  },
  {
    id: "reading-a-book",
    title: "Open a book & get around",
    featureKey: "reading",
    keywords: [
      "read", "reading", "open", "book", "library", "tabs", "navigate", "menu",
      "topic", "lesson", "export", "epub", "pdf", "tour", "studio", "shelf",
      "quiz", "question", "answer", "reveal", "score",
    ],
    blocks: [
      {
        kind: "text",
        text: "Mentible has five places along the top of the app: Library (your finished books), Studio (create and edit books), Settings (your LLM keys and preferences), Help (guides and these walkthroughs), and About (version and privacy).",
      },
      {
        kind: "steps",
        steps: [
          "Open Library and tap a book cover to open it.",
          "Inside the book, tap a topic to read its lesson.",
          "Use Export to save the book as an EPUB or PDF for offline reading.",
        ],
      },
      {
        kind: "text",
        text: "New here? Your Library already has a book ready to open, so you can start reading before authoring anything of your own.",
      },
      {
        kind: "text",
        text: "Quizzes inside a book are interactive: tap an option to answer. Your choice locks in, the correct answer is highlighted, and the explanation appears so you can check your reasoning.",
      },
      { kind: "action", label: "Replay the app tour", step: "tour" },
    ],
  },
  {
    id: "scoped-generation",
    title: "How scoping works",
    featureKey: "generation",
    keywords: ["scope", "scoped", "level", "depth", "length", "parameters", "chatbot"],
    blocks: [
      {
        kind: "text",
        text: "Mentible isn't a chatbot. Every topic is generated with a scoped request tuned by a few dimensions — level, depth, length and diagram register — a real lesson inside your book, not a chat reply. Adjust the scope to change the reading level, how deep it goes, and the kind of diagrams it produces.",
      },
    ],
  },
  {
    id: "diagram-types",
    title: "Diagram types",
    featureKey: "diagrams",
    keywords: ["diagram", "visual", "register", "conceptual", "balanced", "technical", "mindmap", "flowchart"],
    blocks: [
      {
        kind: "text",
        text: "The Diagrams setting controls what kind of visuals you get — from big-idea infographics to precise technical diagrams. Browse examples to pick the direction that fits your audience.",
      },
      { kind: "link", label: "Browse diagram types →", href: "/diagram-types" },
    ],
  },
  {
    id: "formats",
    title: "Formats & books",
    featureKey: "export",
    keywords: ["format", "epub", "pdf", "book", "compile", "library", "export", "cover"],
    blocks: [
      {
        kind: "text",
        text: "Each topic is generated as a lesson and compiled into an EPUB/PDF book with a branded cover, figures, tables and a glossary, shown on your Library shelf.",
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    keywords: ["error", "fail", "failed", "problem", "timeout", "offline", "broken", "fix", "faq"],
    blocks: [
      {
        kind: "defs",
        defs: [
          {
            term: "“No API key set”",
            def: "Open Settings and paste your Anthropic key (starts with sk-ant-). It is stored only on your device.",
          },
          {
            term: "Generation failed or timed out",
            def: "Check your connection and that your key is valid and has credit, then try again. Large page targets take longer.",
          },
          {
            term: "Key rejected",
            def: "Re-check the key in Settings — it must be an Anthropic key beginning with sk-ant-. Re-enter it if you recently rotated it.",
          },
          {
            term: "Nothing happens offline",
            def: "Generation needs a connection (it calls Anthropic). Books already saved to your Library open offline.",
          },
        ],
      },
    ],
  },
  {
    id: "share-a-draft",
    title: "Share a draft for feedback",
    featureKey: "sharing",
    keywords: [
      "share",
      "sharing",
      "draft",
      "review",
      "reviewer",
      "comment",
      "feedback",
      "invite",
      "shared with you",
      "collaborate",
    ],
    blocks: [
      {
        kind: "text",
        text: "Share a work-in-progress book with specific people, get their comments, and reply — all inside Mentible. It's invite-only: you invite reviewers by email, and they see the draft after signing in with that same email.",
      },
      { kind: "text", text: "For authors — share and collect feedback:" },
      {
        kind: "steps",
        steps: [
          "Open a book you authored, then tap “Share draft”.",
          "Under Reviewers, enter a person's email and tap Invite (add as many as you like).",
          "Tell your reviewers a draft is waiting — the app doesn't email them.",
          "When they comment, a 💬 badge appears on the book in Studio — tap it to read their comments and reply.",
        ],
      },
      { kind: "text", text: "For reviewers — read and comment:" },
      {
        kind: "steps",
        steps: [
          "Sign in with the exact email you were invited at.",
          "On the Library tab, open the “Shared with you” section.",
          "Tap the draft to read it full-screen.",
          "Leave a comment — the author sees it and can reply.",
        ],
      },
      {
        kind: "text",
        text: "Good to know: reviewers need a (free) account — no guest access yet; comments attach to the version reviewed; and the lists refresh when you return to the screen.",
      },
    ],
  },
  {
    id: "glossary",
    title: "Glossary",
    keywords: ["glossary", "term", "definition", "meaning", "katex", "mermaid"],
    blocks: [
      {
        kind: "defs",
        defs: [
          { term: "BYOK", def: "Bring Your Own Key — you supply your Anthropic API key and are billed by Anthropic directly." },
          { term: "Scoped generation", def: "A generation request parametrised by level, depth, length, language and diagram register — the core model of the app." },
          { term: "Diagram register", def: "The chosen direction of a book's visuals: Conceptual, Balanced, or Technical." },
          { term: "EPUB3 / PDF", def: "The compiled book formats Mentible produces, with a cover, figures, tables and a glossary." },
          { term: "KaTeX", def: "The math typesetting used to render formulas in lessons." },
          { term: "Mermaid", def: "The text-to-diagram syntax used to render flowcharts and other technical diagrams." },
        ],
      },
    ],
  },
  {
    id: "plans",
    title: "Plans & billing",
    keywords: ["plan", "plans", "billing", "subscription", "price", "pricing", "managed", "byok", "cancel", "restore"],
    featureKey: "plans",
    blocks: [
      {
        kind: "text",
        text: "Paid plans aren't available yet — this screen is a preview. Bring-your-own-key works today: add a provider key in Settings and start generating.",
      },
      {
        kind: "text",
        text: "Mentible gives you two ways to pay for the AI that writes your books. Both let you read, author, and export — they differ in who holds the provider key and who pays for tokens.",
      },
      {
        kind: "defs",
        defs: [
          {
            term: "Managed",
            def: "We hold the provider key and carry the token cost. Your plan includes a monthly generation allowance; when it runs out you can add your own key or wait for the period to renew. No API key to set up.",
          },
          {
            term: "Bring your own key (BYOK)",
            def: "You add your own provider key in Settings and pay that provider directly for tokens. We never see a bill for your generation, and we set no limit on it. Your key is stored in your device's secure storage.",
          },
        ],
      },
      {
        kind: "text",
        text: "Adding your own key never moves it into our managed vault — a BYOK key stays yours and stays on your device. The two paths are separate on purpose.",
      },
      {
        kind: "text",
        text: "Subscriptions renew automatically. Cancel any time in Google Play (Play Store → Payments & subscriptions), not in Mentible. Cancelling leaves your books and your Library untouched; managed generation falls back to your own key.",
      },
      {
        kind: "text",
        text: "Changed device or reinstalled? Use Restore on the Plans screen to bring back a subscription you already bought.",
      },
      { kind: "link", label: "See plans →", href: "/paywall" },
    ],
  },
  {
    id: "attach-figures",
    title: "Add figures to a topic",
    featureKey: "figures",
    keywords: ["image", "figure", "photo", "picture", "attach", "diagram", "camera", "media"],
    blocks: [
      {
        kind: "text",
        text: "You can attach images — a photo, a diagram, a scan — to any topic that already has content. They appear in a Figures section when you read the topic and are included when you export the book. Your figures stay on your device; nothing is sent to the AI.",
      },
      {
        kind: "text",
        text: "Because figures stay on your device, they aren't included when you share a draft with a reviewer — the reviewer sees a note saying some figures aren't shown. To send someone your figures, export the book as EPUB or PDF and share that instead.",
      },
      {
        kind: "text",
        text: "Each figure takes a caption and alt text. The caption is shown under the figure for everyone. The alt text is what someone using a screen reader hears instead of the image, so describe what it shows — \"a circular diagram of the eight steps\" rather than \"Figure 1\". If you leave alt text empty we fall back to the caption, and then to a plain label like \"Figure 1\".",
      },
      {
        kind: "steps",
        steps: [
          "Open a topic that has generated content.",
          "Tap Add figure, then Choose from library or Take photo.",
          "Add an optional caption. The image is saved on your device.",
          "Export the book to include your figures in the EPUB or PDF.",
        ],
      },
      {
        kind: "defs",
        defs: [
          { term: "Supported formats", def: "JPEG, PNG and WebP, up to 10 MB each." },
          { term: "Where are my images stored?", def: "On your device only. Location data (EXIF/GPS) is stripped automatically." },
        ],
      },
    ],
  },
];
