import type { HelpTopic } from "@/help";
import { providerKeyDefs } from "./providerDefs";

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: "home-and-nav",
    title: "Home & navigation",
    featureKey: "landing-home",
    keywords: [
      "home", "landing", "navigation", "nav", "top bar", "sign in", "menu",
      "capture", "create", "validate", "share", "front door", "start",
    ],
    blocks: [
      {
        kind: "text",
        text: "Home is Mentible's front door. It explains what the app does — an expert-validation studio that moves work through Capture → Create → Validate → Share — shows the formats you can produce, and points you to where to start, whether that's reading a book already in your Library or starting a new project.",
      },
      {
        kind: "text",
        text: "Before you sign in, the top bar shows marketing links plus a Sign in button. Once you're signed in, those links are replaced by your app tabs — Library, Studio, Projects, Reviews, and Publish — alongside an account menu (Settings, Help, About, Sign out).",
      },
      {
        kind: "steps",
        steps: [
          "From Home, tap Sign in to create an account or log in.",
          "Once signed in, use the top bar's tabs to get to your Library, Studio, Projects, Reviews, or Publish.",
          "Open the account menu for Settings, Help, About, or to sign out.",
        ],
      },
    ],
  },
  {
    id: "getting-started",
    title: "Getting started",
    keywords: ["start", "begin", "first", "setup", "onboard", "books", "library"],
    blocks: [
      {
        kind: "text",
        text: "Mentible turns what you want to learn into a real, readable book, generated by an AI model you connect. Two finished books are already in your Library — open them right now, no account or key needed. When you're ready to make your own, here's the path:",
      },
      {
        kind: "steps",
        steps: [
          "Optional: sign in to sync your library across devices — or keep reading without an account.",
          "Add a provider API key in Settings. Claude (Anthropic) is recommended for finished books; free tiers exist if you just want to try it. Your key stays on your device.",
          "In Books, start a New Book and structure its table of contents.",
          "Generate — each topic is written with math, diagrams and tables, scoped by level and depth.",
          "Save the finished book to your Library to read or export.",
        ],
      },
      { kind: "action", label: "Create your account", step: "signup" },
      { kind: "action", label: "Add an API key", step: "key" },
    ],
  },
  {
    id: "getting-started-account",
    title: "Create your account & sign in",
    featureKey: "accounts",
    keywords: [
      "account", "sign in", "signin", "sign up", "signup", "login", "log in",
      "register", "google", "email", "password", "confirm", "verify", "sync",
    ],
    blocks: [
      {
        kind: "text",
        text: "An account is optional but recommended — it syncs your library and provider settings across your devices. There are two ways to create one: continue with Google, or sign up with an email and password (no Google account needed). You can always read the included books and use a BYOK key without any account.",
      },
      {
        kind: "text",
        text: "Option 1 — Continue with Google",
      },
      {
        kind: "steps",
        steps: [
          "On the sign-in screen (or the first-run wizard), tap “Continue with Google”.",
          "A Google window opens — choose your Google account and approve access.",
          "You’re returned to Mentible, now signed in. Your library and provider settings then sync automatically.",
        ],
      },
      {
        kind: "text",
        text: "Option 2 — Email & password (no Google account needed)",
      },
      {
        kind: "steps",
        steps: [
          "On the sign-in screen, choose “Create account”.",
          "Enter your email address and a password (at least 6 characters), then tap “Create account”.",
          "Open the confirmation email from Mentible and tap the link to verify (check your spam folder if it isn’t there).",
          "Return to Mentible and “Sign in” with that email and password. Your library and settings then sync.",
        ],
      },
      { kind: "action", label: "Start the sign-up walkthrough", step: "signup" },
      {
        kind: "defs",
        defs: [
          {
            term: "Didn't get the confirmation email",
            def: "Check your spam folder and that the address is correct. Re-running sign-up resends the link.",
          },
          {
            term: "“Continue with Google” did nothing",
            def: "The sign-in browser was likely dismissed. Tap Continue with Google again and complete the Google prompt.",
          },
          {
            term: "Sign-in isn't available",
            def: "Some builds (including the demo) run without accounts — you can still read the included books and use a BYOK key without signing in.",
          },
        ],
      },
      { kind: "link", label: "Open sign-in →", href: "/sign-in" },
    ],
  },
  {
    id: "provider-keys",
    title: "Choose a provider & get an API key",
    featureKey: "provider-keys",
    keywords: [
      "key", "api", "byok", "provider", "anthropic", "claude", "openai", "groq",
      "openrouter", "gemini", "google", "free", "paid", "billing", "cost",
    ],
    blocks: [
      {
        kind: "text",
        text: "Mentible is bring-your-own-key (BYOK): you connect your own LLM account and are billed by that provider directly. Your key is stored in your device's secure storage and sent per request — never logged or stored on a server. You can add more than one provider and switch between them in Settings.",
      },
      {
        kind: "text",
        text: "Want to try it free? Groq, Google Gemini and OpenRouter all have free tiers (output is draft-grade). Anthropic (Claude) gives the best quality for finished books but is paid.",
      },
      { kind: "defs", defs: providerKeyDefs() },
      {
        kind: "steps",
        steps: [
          "In Settings (or the first-run wizard), pick a provider.",
          "Open that provider's console using the link and create an API key.",
          "Copy the key and paste it into the key field — it's checked for the right shape and saved on your device.",
          "Your key is verified the first time you generate; if it's wrong you'll see a clear error.",
        ],
      },
      { kind: "action", label: "Start the API-key walkthrough", step: "key" },
      { kind: "link", label: "Open Settings →", href: "/settings" },
    ],
  },
  {
    id: "ai-model",
    title: "Which AI writes your book",
    featureKey: "ai-model",
    keywords: [
      "model", "ai", "llm", "provider", "default", "groq", "llama", "claude",
      "anthropic", "free", "byok", "key", "quality", "switch", "change",
    ],
    blocks: [
      {
        kind: "text",
        text: "By default Mentible writes with a free, fast model (Llama 3.3, via Groq) — no API key needed. It's great for drafting; output is draft-grade, which is why you review and (for validated work) approve it before it counts.",
      },
      {
        kind: "text",
        text: "Prefer the highest quality? If you know your way around AI tools, connect your own Anthropic (Claude) key — or another provider — in Settings, and pick it as the model for a book. Then you're billed by that provider directly (bring-your-own-key), and your key stays on your device.",
      },
      {
        kind: "steps",
        steps: [
          "Start a book — it uses the free default automatically.",
          "To upgrade quality, open Settings and add your own provider key (e.g. Anthropic / Claude).",
          "In the book's generation settings, choose that provider as the model.",
          "New books remember your choice; you can override it per book.",
        ],
      },
      { kind: "link", label: "Open Settings →", href: "/settings" },
    ],
  },
  {
    id: "reading-a-book",
    title: "Open a book & get around",
    featureKey: "reading",
    keywords: [
      "read", "reading", "open", "book", "library", "tabs", "navigate", "menu",
      "topic", "lesson", "export", "epub", "pdf", "tour", "studio", "shelf",
      "quiz", "question", "answer", "reveal", "score",
    ],
    blocks: [
      {
        kind: "text",
        text: "Mentible's nav bar has: Library (your finished books), Projects (the expert-validation studio), Reviews (projects you've been invited to review), Publish (turn your writing into posts and shareable cards), Settings (your LLM keys and preferences), Help (guides and these walkthroughs), and About (version and privacy).",
      },
      {
        kind: "steps",
        steps: [
          "Open Library and tap a book cover to open it.",
          "Inside the book, tap a topic to read its lesson.",
          "Use Export to save the book as an EPUB or PDF for offline reading.",
        ],
      },
      {
        kind: "text",
        text: "New here? Your Library already has a book ready to open, so you can start reading before authoring anything of your own.",
      },
      {
        kind: "text",
        text: "Quizzes inside a book are interactive: tap an option to answer. Your choice locks in, the correct answer is highlighted, and the explanation appears so you can check your reasoning.",
      },
      { kind: "action", label: "Replay the app tour", step: "tour" },
    ],
  },
  {
    id: "scoped-generation",
    title: "How scoping works",
    featureKey: "generation",
    keywords: ["scope", "scoped", "level", "depth", "length", "parameters", "chatbot"],
    blocks: [
      {
        kind: "text",
        text: "Mentible isn't a chatbot. Every topic is generated with a scoped request tuned by a few dimensions — level, depth, length and diagram register — a real lesson inside your book, not a chat reply. Adjust the scope to change the reading level, how deep it goes, and the kind of diagrams it produces.",
      },
    ],
  },
  {
    id: "diagram-types",
    title: "Diagram types",
    featureKey: "diagrams",
    keywords: ["diagram", "visual", "register", "conceptual", "balanced", "technical", "mindmap", "flowchart"],
    blocks: [
      {
        kind: "text",
        text: "The Diagrams setting controls what kind of visuals you get — from big-idea infographics to precise technical diagrams. Browse examples to pick the direction that fits your audience.",
      },
      { kind: "link", label: "Browse diagram types →", href: "/diagram-types" },
    ],
  },
  {
    id: "formats",
    title: "Formats & books",
    featureKey: "export",
    keywords: ["format", "epub", "pdf", "book", "compile", "library", "export", "cover"],
    blocks: [
      {
        kind: "text",
        text: "Each topic is generated as a lesson and compiled into an EPUB/PDF book with a branded cover, figures, tables and a glossary, shown on your Library shelf.",
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    keywords: ["error", "fail", "failed", "problem", "timeout", "offline", "broken", "fix", "faq"],
    blocks: [
      {
        kind: "defs",
        defs: [
          {
            term: "“No API key set”",
            def: "Open Settings and paste your Anthropic key (starts with sk-ant-). It is stored only on your device.",
          },
          {
            term: "Generation failed or timed out",
            def: "Check your connection and that your key is valid and has credit, then try again. Large page targets take longer.",
          },
          {
            term: "Key rejected",
            def: "Re-check the key in Settings — it must be an Anthropic key beginning with sk-ant-. Re-enter it if you recently rotated it.",
          },
          {
            term: "Nothing happens offline",
            def: "Generation needs a connection (it calls Anthropic). Books already saved to your Library open offline.",
          },
        ],
      },
    ],
  },
  {
    id: "share-a-draft",
    title: "Share a draft for feedback",
    featureKey: "sharing",
    keywords: [
      "share",
      "sharing",
      "draft",
      "review",
      "reviewer",
      "comment",
      "feedback",
      "invite",
      "shared with you",
      "collaborate",
    ],
    blocks: [
      {
        kind: "text",
        text: "Share a work-in-progress book with specific people, get their comments, and reply — all inside Mentible. It's invite-only: you invite reviewers by email, and they see the draft after signing in with that same email.",
      },
      { kind: "text", text: "For authors — share and collect feedback:" },
      {
        kind: "steps",
        steps: [
          "Open a book you authored, then tap “Share draft”.",
          "Under Reviewers, enter a person's email and tap Invite (add as many as you like).",
          "Tell your reviewers a draft is waiting — the app doesn't email them.",
          "When they comment, a 💬 badge appears on the book's card in your Library — tap it to read their comments and reply.",
        ],
      },
      { kind: "text", text: "For reviewers — read and comment:" },
      {
        kind: "steps",
        steps: [
          "Sign in with the exact email you were invited at.",
          "On the Library tab, open the “Shared with you” section.",
          "Tap the draft to read it full-screen.",
          "Leave a comment — the author sees it and can reply.",
        ],
      },
      {
        kind: "text",
        text: "Good to know: reviewers need a (free) account — no guest access yet; comments attach to the version reviewed; and the lists refresh when you return to the screen.",
      },
    ],
  },
  {
    id: "glossary",
    title: "Glossary",
    keywords: ["glossary", "term", "definition", "meaning", "katex", "mermaid"],
    blocks: [
      {
        kind: "defs",
        defs: [
          { term: "BYOK", def: "Bring Your Own Key — you supply your Anthropic API key and are billed by Anthropic directly." },
          { term: "Scoped generation", def: "A generation request parametrised by level, depth, length, language and diagram register — the core model of the app." },
          { term: "Diagram register", def: "The chosen direction of a book's visuals: Conceptual, Balanced, or Technical." },
          { term: "EPUB3 / PDF", def: "The compiled book formats Mentible produces, with a cover, figures, tables and a glossary." },
          { term: "KaTeX", def: "The math typesetting used to render formulas in lessons." },
          { term: "Mermaid", def: "The text-to-diagram syntax used to render flowcharts and other technical diagrams." },
        ],
      },
    ],
  },
  {
    id: "plans",
    title: "Plans & billing",
    keywords: ["plan", "plans", "billing", "subscription", "price", "pricing", "managed", "byok", "cancel", "restore"],
    featureKey: "plans",
    blocks: [
      {
        kind: "text",
        text: "Paid plans aren't available yet — this screen is a preview. Bring-your-own-key works today: add a provider key in Settings and start generating.",
      },
      {
        kind: "text",
        text: "Mentible gives you two ways to pay for the AI that writes your books. Both let you read, author, and export — they differ in who holds the provider key and who pays for tokens.",
      },
      {
        kind: "defs",
        defs: [
          {
            term: "Managed",
            def: "We hold the provider key and carry the token cost. Your plan includes a monthly generation allowance; when it runs out you can add your own key or wait for the period to renew. No API key to set up.",
          },
          {
            term: "Bring your own key (BYOK)",
            def: "You add your own provider key in Settings and pay that provider directly for tokens. We never see a bill for your generation, and we set no limit on it. Your key is stored in your device's secure storage.",
          },
        ],
      },
      {
        kind: "text",
        text: "Adding your own key never moves it into our managed vault — a BYOK key stays yours and stays on your device. The two paths are separate on purpose.",
      },
      {
        kind: "text",
        text: "Subscriptions renew automatically. Cancel any time in Google Play (Play Store → Payments & subscriptions), not in Mentible. Cancelling leaves your books and your Library untouched; managed generation falls back to your own key.",
      },
      {
        kind: "text",
        text: "Changed device or reinstalled? Use Restore on the Plans screen to bring back a subscription you already bought.",
      },
      { kind: "link", label: "See plans →", href: "/paywall" },
    ],
  },
  {
    id: "attach-figures",
    title: "Add figures to a topic",
    featureKey: "figures",
    keywords: ["image", "figure", "photo", "picture", "attach", "diagram", "camera", "media"],
    blocks: [
      {
        kind: "text",
        text: "You can attach images — a photo, a diagram, a scan — to any topic that already has content. They appear in a Figures section when you read the topic and are included when you export the book. Your figures stay on your device; nothing is sent to the AI.",
      },
      {
        kind: "text",
        text: "Because figures stay on your device, they aren't included when you share a draft with a reviewer — the reviewer sees a note saying some figures aren't shown. To send someone your figures, export the book as EPUB or PDF and share that instead.",
      },
      {
        kind: "text",
        text: "Each figure takes a caption and alt text. The caption is shown under the figure for everyone. The alt text is what someone using a screen reader hears instead of the image, so describe what it shows — \"a circular diagram of the eight steps\" rather than \"Figure 1\". If you leave alt text empty we fall back to the caption, and then to a plain label like \"Figure 1\".",
      },
      {
        kind: "steps",
        steps: [
          "Open a topic that has generated content.",
          "Tap Add figure, then Choose from library or Take photo.",
          "Add an optional caption. The image is saved on your device.",
          "Export the book to include your figures in the EPUB or PDF.",
        ],
      },
      {
        kind: "defs",
        defs: [
          { term: "Supported formats", def: "JPEG, PNG and WebP, up to 10 MB each." },
          { term: "Where are my images stored?", def: "On your device only. Location data (EXIF/GPS) is stripped automatically." },
        ],
      },
    ],
  },
  {
    id: "reader-audio",
    title: "Listening to a book's narration",
    featureKey: "reader-audio",
    keywords: ["audio", "narration", "listen", "play", "pause", "seek", "transcript", "voice", "sound", "reader"],
    blocks: [
      {
        kind: "text",
        text: "When a topic carries narration, an audio player appears inside the reader — on the web app and on Android — right alongside the topic's text. This isn't a separate app or a download: audio is part of our reader, one more rung of the multi-modal library alongside text and figures.",
      },
      {
        kind: "text",
        text: "The transcript is always available underneath the player, so you can read along or skip listening entirely without losing anything.",
      },
      {
        kind: "steps",
        steps: [
          "Open a topic that has narration attached.",
          "Tap Play to start listening; tap again to pause.",
          "Drag the seek bar, or tap anywhere on it, to jump to a point in the clip.",
          "Elapsed and total time are shown next to the transport controls.",
          "Playing a different clip automatically stops whatever was already playing.",
        ],
      },
      {
        kind: "text",
        text: "Narration is generated from a topic's text, not recorded — create it with \"Generate narration\" in the topic editor (see \"Generating narration for a topic\"), or it can arrive with an imported book. The reader plays it; it doesn't record.",
      },
    ],
  },
  {
    id: "narrate-topic",
    title: "Generating narration for a topic",
    featureKey: "narrate-topic",
    keywords: ["narrate", "narration", "audio", "generate", "voice", "openai", "tts", "text-to-speech", "topic editor", "generate all narration"],
    blocks: [
      {
        kind: "text",
        text: "You can turn any topic's text into a spoken audio clip right from the topic editor. Tap \"Generate narration\" and Mentible reads the topic's content aloud with a text-to-speech voice, then attaches the clip to that topic — it plays back in the reader (alongside the transcript) and is bundled in when you export the book.",
      },
      {
        kind: "text",
        text: "To narrate a whole book in one pass, open the book's screen and use \"Generate all narration\". It's resumable: topics that already have a clip are skipped, so if you stop partway through or add new topics later, running it again only narrates what's still missing.",
      },
      {
        kind: "text",
        text: "Narration uses your own OpenAI key (Settings) — it's the same key used for other text-to-speech features, and today it only works BYOK: the managed plan's token allowance doesn't cover audio narration yet.",
      },
      {
        kind: "steps",
        steps: [
          "Add your OpenAI key in Settings, if you haven't already.",
          "Open a topic in the topic editor and tap \"Generate narration\" for a single clip, or",
          "Open the book's screen and tap \"Generate all narration\" to narrate every topic that doesn't already have a clip.",
          "Play back a clip from the topic editor or the reader; it's included automatically when you export the book.",
        ],
      },
    ],
  },
  {
    id: "backup-restore",
    title: "Backup & restore your library",
    featureKey: "backup-restore",
    keywords: ["backup", "restore", "export library", "import", "migrate", "new device", "mentible.app", "settings"],
    blocks: [
      {
        kind: "text",
        text: "Settings → Backup & Restore lets you save your whole library to a single file and bring it back later — the way to move your library to a new device, or to the new mentible.app site.",
      },
      {
        kind: "text",
        text: "\"Export library\" downloads a .mentible-backup file containing your authored books, your saved reader EPUBs, your shelves, and your generation settings. It does NOT include your API key — re-enter that in Settings after restoring on a new device.",
      },
      {
        kind: "text",
        text: "\"Restore from backup\" imports a .mentible-backup file. It overwrites any book or EPUB that shares an id with something already in your library, so it asks you to confirm before importing.",
      },
      {
        kind: "steps",
        steps: [
          "Open Settings and find the \"Backup & Restore\" section.",
          "Tap \"Export library\" to download a .mentible-backup file of your books, EPUBs, shelves, and generation settings.",
          "On the new device or site, open Settings → Backup & Restore and tap \"Restore from backup\", then pick that file.",
          "Confirm the import when asked — items that match an existing id are overwritten.",
          "Re-enter your API key in Settings; it isn't included in the backup.",
        ],
      },
    ],
  },
  {
    id: "library-sync",
    title: "Cloud sync — keep your library on all your devices",
    featureKey: "library-sync",
    keywords: ["sync", "cloud", "encrypted", "end-to-end", "recovery key", "new device", "devices", "backup", "mentible.app", "settings"],
    blocks: [
      {
        kind: "text",
        text: "Cloud sync keeps your authored books on every device you sign in on. Turn it on in Settings → Sync, then tap \"Sync now\" to push and pull your library.",
      },
      {
        kind: "text",
        text: "Your books are encrypted on your device before they're uploaded — end-to-end. We store only the encrypted data and can never read your library.",
      },
      {
        kind: "text",
        text: "When you enable sync you get a one-time recovery key. Save it. It's the ONLY way to unlock sync on a new device, and we can't recover it for you. Your exported EPUB/PDF is your fallback if you lose it.",
      },
      {
        kind: "steps",
        steps: [
          "On your first device, open Settings → Sync and tap \"Enable cloud sync\". Copy and save the recovery key it shows once.",
          "Tap \"Sync now\" to upload your library.",
          "On a new device, sign in, open Settings → Sync, and enter your recovery key to unlock, then Sync now.",
        ],
      },
      {
        kind: "text",
        text: "Sync now covers your authored books, your reader EPUBs, and your shelves — all end-to-end encrypted the same way. Your API key is not part of sync — use Backup & Restore for that.",
      },
      {
        kind: "text",
        text: "A very large EPUB (over 50 MB) may not sync, and neither will one that would put you over your account's 500 MB sync storage limit. \"Sync now\" names which book(s) were skipped and why — free up space or remove synced books, then sync again.",
      },
      {
        kind: "text",
        text: "Sync now runs automatically once it's enabled and unlocked on a device — when you sign in, when you reopen the app, and a few seconds after you edit a book. You can also still tap \"Sync now\" any time.",
      },
      {
        kind: "text",
        text: "Settings → Sync shows the status: \"Up to date\" when local matches the server, a count when there are changes to sync, \"Syncing…\" while it runs, or \"Couldn't sync — will retry\" on a temporary error. Turn off \"Auto-sync\" there if you'd rather sync only with the button.",
      },
      {
        kind: "text",
        text: "If two devices edit the same book, the most recently saved version wins when they sync (last-write-wins) — there's no merge or conflict prompt.",
      },
    ],
  },
  {
    id: "projects",
    title: "What a project is — and how to start one",
    featureKey: "projects",
    keywords: ["project", "expert", "knowledge", "capture", "create", "validate", "share", "trust", "phase", "tab", "role", "owner", "reviewer", "editor", "banner"],
    blocks: [
      {
        kind: "text",
        text: "A project is Mentible's expert-validation studio: you capture an expert's raw knowledge, turn it into a draft, have an expert validate it, then share the validated result. \"Trust is the product\" — every project moves through the same four-phase loop: Capture → Create → Validate → Share.",
      },
      {
        kind: "text",
        text: "The project screen has five tabs, one per stage of that loop: Input (capture sources), Structure (build the outline), Drafts (generate content), Feedback (review & approve), and Publish (export the validated result). An adaptive banner at the top of the screen always tells you the single next thing to do, and the screen opens on whichever tab you're currently in — so you never have to guess where a project stands. Tap any tab to jump to a different phase; Back/Next at the bottom move you through them in order.",
      },
      {
        kind: "text",
        text: "Three roles work a project: the Owner (who created it) can edit sources, structure and drafts, and invite people; an invited Reviewer can approve, withdraw an approval, and comment, but can't edit; an invited Editor edits the draft text and creates new versions instead of approving — the two invited roles are separate, an Editor can't approve and a Reviewer can't edit. Everyone with access sees the same project — the tabs just show or hide actions based on your role.",
      },
      {
        kind: "steps",
        steps: [
          "On the Projects tab, tap \"+ New project\".",
          "Fill in Title (required), and optionally Topic, Audience and Goal — these steer tone, not content.",
          "Add your source material on the Input tab.",
          "Follow the banner's next step through Structure, Drafts, Feedback and Publish.",
        ],
      },
    ],
  },
  {
    id: "word-export",
    title: "Download a validated master as Word",
    featureKey: "word-export",
    keywords: ["word", "docx", "export", "download", "pro", "publish", "editable", "office"],
    blocks: [
      {
        kind: "text",
        text: "On the Publish tab, a Pro plan can download a book or guide asset's expert-validated version as an editable Word (.docx) document — alongside the existing EPUB and PDF downloads — so you can drop it straight into your own editing, formatting, or submission workflow outside Mentible.",
      },
      {
        kind: "text",
        text: "Word export compiles from the same validated master as EPUB/PDF: headings, prose, tables, and math/diagrams (rendered as images) all carry over. It's only offered for long-form assets (book, essay, guide) — short social assets (LinkedIn post, thread, etc.) stay Copy/Copy-as-Markdown only, since they have no compiled file to export.",
      },
      {
        kind: "defs",
        defs: [
          { term: "Where's the button?", def: "Publish tab → the long-form asset's card (or, once the project has a table of contents, the whole-book \"Per topic\" view) → \"Download Word\", beside \"Download EPUB\" and \"Download PDF\"." },
          { term: "Not seeing it?", def: "Word export is a Pro plan feature. If it's missing, either you're on a Free plan (upgrade from the Usage screen) or your plan doesn't include it yet — the download still works if you try it and are actually entitled; the button is a convenience, not the real gate." },
          { term: "Does it change what's published?", def: "No — it's a read-only export of the already-validated content, same as EPUB/PDF." },
        ],
      },
    ],
  },
  {
    id: "kdp-export",
    title: "Export a KDP-clean EPUB for Kindle",
    featureKey: "kdp-export",
    keywords: ["kdp", "kindle", "amazon", "export", "epub", "epubcheck", "publish"],
    blocks: [
      {
        kind: "text",
        text: "\"Kindle (KDP)\" produces a separate, distribution-ready EPUB tuned for Amazon KDP: math and diagrams are rendered as images instead of MathML/SVG (Kindle's support for both is inconsistent), the cover is a raster JPEG instead of the app's vector cover, and the body no longer forces our house font — Kindle's reading system controls that. It's a different file from your regular EPUB/PDF checkout, not a setting on it.",
      },
      {
        kind: "defs",
        defs: [
          { term: "Where's the button?", def: "On a Library book's Check out panel, next to EPUB3 and PDF: \"Kindle (KDP)\"." },
          { term: "Why does it need a released book?", def: "KDP exports refuse a draft book — release it first (clears the \"DRAFT\" watermark) so what you upload to KDP is the finished edition." },
          { term: "Does it change what's published?", def: "No — it's a separate, read-only export tuned for one destination. Your regular EPUB/PDF checkout is unaffected." },
        ],
      },
    ],
  },
  {
    id: "publish-pack",
    title: "Download a publish pack for retailers",
    featureKey: "publish-pack",
    keywords: ["publish", "pack", "kdp", "draft2digital", "publishdrive", "retailer", "export", "metadata"],
    blocks: [
      {
        kind: "text",
        text: "\"Publish pack\" downloads one zip with everything you need to hand this book to a retailer: the KDP-clean EPUB, its cover as a plain JPEG, a metadata sheet listing the fields Mentible stores (plus labeled blanks for the ones it doesn't — subtitle, keywords, categories), and a README with step-by-step upload links for Amazon KDP, Draft2Digital, and PublishDrive. There's still no automatic submission — you upload it yourself, but it's one download and a copy-paste instead of hunting down each file.",
      },
      {
        kind: "defs",
        defs: [
          { term: "Where's the button?", def: "On a Library book's Check out panel, next to EPUB3, PDF, and Kindle (KDP): \"Publish pack\"." },
          { term: "Why does it need a released book?", def: "The pack's EPUB is the same KDP-clean export, which refuses a draft book — release it first (clears the \"DRAFT\" watermark)." },
          { term: "What about Apple Books?", def: "Apple's direct upload needs a Mac and their Transporter app, so the README doesn't link it — it points you to Draft2Digital instead, which reaches Apple Books without a Mac." },
        ],
      },
    ],
  },
  {
    id: "epub2-export",
    title: "Export an EPUB 2 for maximum compatibility",
    featureKey: "epub2-export",
    keywords: ["epub2", "epub 2", "compatibility", "old reader", "export", "epubcheck"],
    blocks: [
      {
        kind: "text",
        text: "\"EPUB 2 (max compatibility)\" produces a separate EPUB tuned for older reading apps and devices that reject the modern EPUB3 files Mentible normally exports. Math and diagrams are rendered as images (same as the Kindle export), and narrated audio can't travel in EPUB 2 at all — instead, the narration's transcript is included as a plain \"Narration (transcript)\" section, so the words survive even though the clip can't. It's a different, more limited file from your regular EPUB3/PDF checkout, not a setting on it — reach for it only if a specific reader or device won't open the regular EPUB.",
      },
      {
        kind: "defs",
        defs: [
          { term: "Where's the button?", def: "On a Library book's Check out panel, next to EPUB3, PDF, Kindle (KDP), and Publish pack: \"EPUB 2 (max compatibility)\"." },
          { term: "What do I lose compared to the regular EPUB?", def: "Rich math/diagram rendering becomes static images, and narrated audio clips are dropped (their transcript replaces them as text). Everything else — chapters, figures, the table of contents — carries over." },
          { term: "Does it change what's published?", def: "No — it's a separate, read-only export for one compatibility need. Your regular EPUB3/PDF checkout is unaffected." },
        ],
      },
    ],
  },
  {
    id: "project-fields",
    title: "New Project fields: Title, Topic, Audience, Goal",
    featureKey: "project-fields",
    keywords: [
      "title", "topic", "audience", "goal", "new project", "field", "fields",
      "limit", "required", "steering", "angle", "prompt", "sources", "grounded",
    ],
    blocks: [
      {
        kind: "text",
        text: "The New Project form has four fields — Title, Topic, Audience, Goal. Only Title is required. The important thing to know: these are STEERING context, not the content itself. They tell the AI the angle and voice of the work; the actual material comes from the Sources (Inputs) you add inside the project afterward. When it generates, the model is told to use only your sources and invent nothing — so Title/Topic/Audience/Goal just frame how it writes what the sources contain. Don't paste your whole subject into Topic; give a short angle here, then feed the real material as Sources.",
      },
      {
        kind: "defs",
        defs: [
          {
            term: "Title  (required · up to 120 characters)",
            def: "The name of the project — what you see in the Projects list. It does not steer generation; make it a clear, human name. E.g. \"Dishwasher drain-pump replacement — DIY guide\".",
          },
          {
            term: "Topic  (optional · up to 500 characters)",
            def: "The specific insight or ANGLE you want — one or two sentences, not the whole subject. This is the field people most often overfill. Keep it to the lens and let the Sources carry the detail. E.g. \"End-to-end drain-pump replacement on a residential dishwasher — safe diagnosis, exact tools and parts, and the common DIY mistakes.\"",
          },
          {
            term: "Audience  (optional)",
            def: "Who the work is for — sets reading level, assumed knowledge, and tone. E.g. \"First-time DIY homeowners with basic hand tools\" or \"Senior engineering leaders\".",
          },
          {
            term: "Goal  (optional)",
            def: "What the reader should be able to do afterward, or why the piece exists. E.g. \"safely replace the pump without a service call\".",
          },
        ],
      },
      {
        kind: "text",
        text: "Behind the scenes each field slots into one line of the prompt: \"…outlining a long-form work ON <topic> FOR <audience> so the reader can <goal>. Using ONLY the sources below…\". A blank field just drops its clause. You can edit any of these later — nothing is locked in at creation.",
      },
      {
        kind: "steps",
        steps: [
          "Title: a clear name (required).",
          "Topic: a short angle — not the full subject.",
          "Audience + Goal: who it's for and what they should get out of it.",
          "Create the project, then add your real material on the Input tab as Sources — that's what the draft is built from.",
        ],
      },
    ],
  },
  {
    id: "reviews",
    title: "The Reviews tab — your invited-project inbox",
    featureKey: "reviews",
    keywords: ["review", "reviews tab", "approve", "expert", "validate", "inbox", "invited"],
    blocks: [
      {
        kind: "text",
        text: "The Reviews tab is your inbox of projects other people have invited you into — it's separate from a project's own Feedback tab, which is where the actual approving happens once you're inside a project. Reviews just lists what's waiting for you.",
      },
      {
        kind: "text",
        text: "Open a project from here to land on its Feedback tab, where you read a draft, approve or request a revision. Approving there marks the version \"expert-validated\" under your name.",
      },
      {
        kind: "steps",
        steps: [
          "Open the Reviews tab to see every project you've been invited to.",
          "Tap a project to open it on its Feedback tab.",
          "Read the draft, then Approve it or Request a revision.",
        ],
      },
    ],
  },
  {
    id: "appearance",
    title: "Appearance & themes",
    featureKey: "appearance",
    keywords: ["theme", "themes", "appearance", "colour", "color", "dark", "light", "sepia", "gilded noir", "forest", "moss"],
    blocks: [
      {
        kind: "text",
        text: "Settings → Appearance lets you pick a colour theme. Themes are curated colour presets — Study (the default), Manuscript (light), Reading (sepia), Gilded Noir, and Forest & Moss. A theme applies instantly across the app and is remembered on this device. It changes only the app's colours; your books and their exports are unaffected.",
      },
    ],
  },
  {
    id: "make-a-post",
    title: "Make a post from your writing",
    featureKey: "make-a-post",
    keywords: ["post", "posts", "share", "linkedin", "x", "twitter", "social", "promote", "publish"],
    blocks: [
      {
        kind: "text",
        text: "The Posts tab turns any writing into short, platform-ready social posts. Paste the source text, pick LinkedIn or X, optionally give it a tone, and you get three distinct drafts to choose from. Each draft is yours to copy and post — Mentible does not publish for you. You can also attach an optional reference image to steer style and tone — the model takes cues from it, it does not copy the image, and your posts are still AI-generated.",
      },
      {
        kind: "steps",
        steps: [
          "Add an Anthropic API key in Settings — the Posts tab uses your key (BYOK).",
          "Open Posts and paste the source text you want to promote.",
          "Choose the platform (LinkedIn or X) and, if you like, a tone.",
          "Make the posts, then copy the draft you want and share it yourself.",
        ],
      },
    ],
  },
  {
    id: "publish-card",
    title: "Publish an image card",
    featureKey: "publish-card",
    keywords: ["publish", "card", "image card", "share", "square", "linkedin", "story", "validated"],
    blocks: [
      {
        kind: "text",
        text: "The Publish tab also makes a branded, shareable image card from your own writing — either pasted text or a validated section from one of your projects. Pick a size (Square, LinkedIn, or Story) and an optional tone; a card built from a validated section carries its cited-source label, so readers can see where it came from. The card is yours to download — Mentible does not publish it for you, and making one uses a billable LLM call (BYOK or your plan's managed allowance).",
      },
      {
        kind: "steps",
        steps: [
          "Open Publish and switch to Image card mode.",
          "Choose a source: paste text, or pick a validated section from your projects.",
          "Pick a size (Square, LinkedIn, or Story) and, if you like, a tone.",
          "Make the card, then download the image to share it yourself.",
        ],
      },
    ],
  },
  {
    id: "publish-carousel",
    title: "Publish a carousel",
    featureKey: "publish-carousel",
    keywords: ["publish", "carousel", "slides", "frames", "image card", "share", "instagram", "linkedin"],
    blocks: [
      {
        kind: "text",
        text: "Carousel mode on the Publish tab turns your own writing into a multi-frame, swipeable image carousel — 4 to 8 branded square frames, built from either pasted text or a validated section from one of your projects. Swipe through the frames to preview them, then download all of them at once as numbered PNGs (frame-1.png, frame-2.png, …) ready to post as a carousel on LinkedIn, Instagram, or wherever you share. Like the image card, a carousel built from a validated section carries its cited-source label, and making one uses a billable LLM call (BYOK or your plan's managed allowance).",
      },
      {
        kind: "steps",
        steps: [
          "Open Publish and switch to Carousel mode.",
          "Choose a source: paste text, or pick a validated section from your projects.",
          "Optionally set a tone, then make the carousel.",
          "Swipe through the frame pager to preview, then Download all to save every frame.",
        ],
      },
    ],
  },
  {
    id: "publish-animated",
    title: "Publish an animated card",
    featureKey: "publish-animated",
    keywords: ["publish", "animated", "gif", "motion", "card", "share", "fade", "slide", "build"],
    blocks: [
      {
        kind: "text",
        text: "Animated mode on the Publish tab turns your own writing into a short, looping animated GIF card — like the image card, but with motion. Choose a motion preset (Fade, Slide-up, or Build-in), built from either pasted text or a validated section from one of your projects. Like the other Publish modes, an animated card built from a validated section carries its cited-source label, and making one uses a billable LLM call (BYOK or your plan's managed allowance). The GIF is yours to download — Mentible does not publish it for you.",
      },
      {
        kind: "steps",
        steps: [
          "Open Publish and switch to Animated mode.",
          "Choose a source: paste text, or pick a validated section from your projects.",
          "Pick a motion preset (Fade, Slide-up, or Build-in) and, if you like, a tone.",
          "Make the animated card, then download the GIF to share it yourself.",
        ],
      },
    ],
  },
  {
    id: "publish-audio",
    title: "Publish narrated audio",
    featureKey: "publish-audio",
    keywords: ["publish", "audio", "narration", "voice", "mp3", "share", "podcast", "listen"],
    blocks: [
      {
        kind: "text",
        text: "Audio mode on the Publish tab turns your own writing into a short narrated audio clip — a spoken summary a text-to-speech voice reads aloud, built from either pasted text or a validated section from one of your projects. Play it back in the app, then download the MP3 to share it yourself. This is a short narrated clip of one section, not a whole-book audiobook. Making one uses a billable LLM call plus a text-to-speech call — narration works with your own OpenAI key today (Settings); Mentible's managed plan doesn't cover audio narration yet.",
      },
      {
        kind: "steps",
        steps: [
          "Open Publish and switch to Audio mode.",
          "Choose a source: paste text, or pick a validated section from your projects.",
          "Optionally set a tone, then make the narration.",
          "Play it back in the app, or Download to save the MP3 and share it yourself.",
        ],
      },
    ],
  },
  {
    id: "sources",
    title: "Input — capture the expert's sources",
    featureKey: "sources",
    keywords: [
      "source",
      "sources",
      "capture",
      "transcript",
      "note",
      "link",
      "input",
      "material",
      "intake",
      "add source",
      "edit",
      "delete",
      "cited",
      "guard",
    ],
    blocks: [
      {
        kind: "text",
        text: "Sources are the raw material a project is built from. On the Input tab, pick a kind — Transcript, Note, or Link — give it an optional Title (or Label, for a Link), then paste its Content (or, for a Link, the URL). The \"Add source\" button enables as soon as the Content — or the URL for a Link — has something in it; the title/label is optional and doesn't gate the button. Add as many as you like; everyone invited to the project can see the full source list, though only the owner can add, edit or delete them.",
      },
      {
        kind: "text",
        text: "Tap a source row to expand it, where Edit and Delete sit. Once a source has been cited by a draft, editing its CONTENT is blocked — the draft's citation would otherwise point at text that no longer says what it said when it was cited. You can still edit its title or reference at any time; only the content is protected, and only once something cites it.",
      },
      {
        kind: "text",
        text: "A Reviewer's Input tab is read-only: they can read every source but can't add, edit or delete one.",
      },
      {
        kind: "text",
        text: "Once at least one source is captured, the owner can move on to Structure to build an outline, or straight to Drafts to generate a first version — either way, everything the model writes is grounded in, and attributed to, these sources.",
      },
      {
        kind: "steps",
        steps: [
          "Choose a source kind: Transcript, Note, or Link.",
          "Paste its Content (or the URL, for a Link) — Title/Label is optional.",
          "Tap \"Add source\" — it enables once Content (or the URL) is filled in.",
          "Tap a source row to Edit or Delete it later.",
        ],
      },
    ],
  },
  {
    id: "draft-viewer",
    title: "Feedback — read, approve, comment & revise a draft",
    featureKey: "draft-viewer",
    keywords: ["draft", "content", "read", "view", "copy", "clipboard", "approve", "unapprove", "withdraw", "feedback", "revision", "request", "note", "edit", "revise", "regenerate", "version", "guidance", "invite", "expert", "editor", "reviewer", "expert-validated", "operator-recorded", "comment"],
    blocks: [
      {
        kind: "text",
        text: "The Feedback tab (like Drafts) has a Whole book / Per topic toggle at the top — pick whichever matches how you're generating this project. Under it, a version list opens the draft viewer, where every action below lives.",
      },
      {
        kind: "text",
        text: "Open a version to read the full drafted content. From here you can Copy the whole draft to your clipboard, leave a Comment on a specific section, and Approve it (or Unapprove it) — the actions sit right on the draft you're reading.",
      },
      {
        kind: "text",
        text: "Approving records the version as validated. There are two ways it happens: a reviewer taps Approve themselves — that's recorded as \"expert-validated\" (self-approved by the invited expert). Or the owner taps Approve, names the expert who signed off outside the app, and taps \"Record approval\" — that's recorded as \"operator-recorded\" (the owner vouching for someone else's sign-off). Both show a provenance chip so anyone reading the project can see which happened. Unapprove withdraws an approval and returns the version to \"awaiting review\" — it appends a withdrawal rather than erasing the earlier approval, so the trust history stays intact.",
      },
      {
        kind: "text",
        text: "\"Invite an expert\" (owner-only) sends someone access to this one project by email: choose whether they join as a Reviewer (can approve, withdraw, and comment — but not edit) or an Editor (edits the draft text and creates new versions instead of approving), enter their email, and send. They gain access the next time they sign in with that email.",
      },
      {
        kind: "text",
        text: "Under the draft, Revision notes is a running, project-wide feedback log, newest first: a reviewer, editor, or the owner can \"Request a revision\" — a short note asking for a change — and every note stays attached to the version it was about.",
      },
      {
        kind: "text",
        text: "The three roles have different edit/generate rights on a draft. The Owner gets everything: Copy, Revise (regenerate a new version from the sources, with optional guidance like \"focus on 2026 costs\" — a billable action against your LLM allowance), Edit text (hand-edit a section's heading and body, then save as a new version), Approve or record an approval, and run the grounding check. An invited Editor can Copy, Edit text (save as a new version), Comment, and Request a revision — but can't tap Revise/Regenerate; that's owner-only. A Reviewer can Copy, Approve (one-tap \"expert-validated\"), Comment, and Request a revision, but can't edit text or regenerate at all.",
      },
      {
        kind: "text",
        text: "Every edit or regeneration is a new version, so an earlier approved version is never changed; the new version needs its own approval. A \"Changes from v{n}\" diff and the full Versions history are available from the draft viewer too.",
      },
    ],
  },
  {
    id: "grounding-report",
    title: "Quality report: coverage, readability & grounding",
    featureKey: "grounding-report",
    keywords: ["quality", "coverage", "readability", "grounding", "grade level", "flesch", "claims", "supported", "unsupported", "cited", "uncited", "dangling", "stale", "re-run"],
    blocks: [
      {
        kind: "text",
        text: "Open a draft version to see its Quality card. Coverage shows how many sections cite a source (for example \"8/10 sections cite a source\"), and flags any uncited sections or dangling citations — a citation pointing at a source that no longer exists.",
      },
      {
        kind: "text",
        text: "Readability shows a grade level and Flesch reading-ease score for the drafted text. Both are directional estimates from a standard formula, not a strict guarantee of how the content reads.",
      },
      {
        kind: "text",
        text: "Grounding is different: it's an on-demand check, not automatic. An owner taps \"Run grounding check\" to have the AI model re-read the draft against its cited sources and score each claim as supported, partial, or unsupported (for example \"41/47 claims supported\"). Because it's a separate, billable pass over the same model you're generating with, it only runs when you ask for it.",
      },
      {
        kind: "text",
        text: "If the draft changes after a grounding check — a new version, an edited section, or an updated source — the existing result is marked stale, with a note to re-run it. Sections with uncited content, a dangling citation, or unsupported claims are annotated inline so you know exactly where to look.",
      },
    ],
  },
  {
    id: "originality-report",
    title: "Originality check: source overlap",
    featureKey: "originality-report",
    keywords: ["originality", "plagiarism", "copyright", "verbatim", "paraphrase", "source overlap", "rights"],
    blocks: [
      {
        kind: "text",
        text: "The originality check audits a draft against ONLY the sources you cited in it — it does not search the web. An owner taps \"Run originality check\" to have the AI model re-read each cited section and flag whether it reproduces the source verbatim, stays close as a paraphrase, or is written in the author's own words (synthesized).",
      },
      {
        kind: "text",
        text: "A section with no cited source has nothing to compare against, so it's automatically counted as original with no LLM call. Like the grounding check, this is a separate, billable pass over your model — it only runs when you ask for it, and a re-run replaces the previous result.",
      },
      {
        kind: "text",
        text: "If the draft or its sources change after a check, the stored result is marked stale, with a note to re-run it.",
      },
      {
        kind: "text",
        text: "This is NOT a plagiarism scan against the internet, and it is not a copyright check — see \"Rights & attribution\" for that. It only tells you how closely your own writing tracks the sources you chose to cite.",
      },
    ],
  },
  {
    id: "project-rights",
    title: "Rights & attribution",
    featureKey: "project-rights",
    keywords: ["rights", "copyright", "attribution", "colophon", "dc:rights", "holder", "attest"],
    blocks: [
      {
        kind: "text",
        text: "On the Publish tab, the project owner can attest \"I hold the rights to the sources I've used and that this is my original work\" and optionally name a rights holder. This is a statement you make, not something Mentible verifies — see the originality check for the closest thing to an automated signal, and note that it only compares against your OWN cited sources, never the web.",
      },
      {
        kind: "text",
        text: "When attested with a rights holder set, the exported EPUB/PDF's copyright page carries a \"© <year> <rights holder>. All rights reserved.\" line. Leaving it unattested doesn't block anything — export always works; the colophon just falls back to a generic line.",
      },
      {
        kind: "text",
        text: "Originality and rights are entirely the author's responsibility. Mentible does not run a plagiarism scan against the internet and does not verify copyright ownership.",
      },
    ],
  },
  {
    id: "generate-full-book",
    title: "Generate the whole book at once",
    featureKey: "generate-full-book",
    keywords: ["generate", "full book", "whole book", "batch", "fan-out", "outline", "toc", "background", "progress", "missing", "estimate", "cost", "tokens"],
    blocks: [
      {
        kind: "text",
        text: "Once your outline (the Structure tab) has topics in it, \"Generate full book\" (on the Drafts tab, under Whole book) drafts every topic in one go instead of one at a time — a full-length draft per topic, written in outline order. It's an owner-only action and only appears once the project has an outline.",
      },
      {
        kind: "text",
        text: "Before it starts, you'll see an estimate — roughly how many tokens the run will use (and, on the managed plan, its approximate cost) — so you can confirm before committing. If you've saved your own Anthropic key (BYOK), the estimate shows tokens only; there's nothing to charge to a managed plan.",
      },
      {
        kind: "text",
        text: "Generation runs in the background, so you can leave the screen — it doesn't block you from doing anything else in the app. Progress shows while it runs, and the result is waiting for you when you come back, listing any topics that failed so you know what to regenerate individually. Only one whole-book run can be active at a time; the button stays disabled until the current run finishes.",
      },
      {
        kind: "text",
        text: "It only fills gaps: topics that already have a draft are skipped, so running it again after adding new topics — or after a run that left some topics failed — generates just what's missing rather than redoing everything.",
      },
    ],
  },
  {
    id: "project-structure",
    title: "Structure — build the outline",
    featureKey: "project-structure",
    keywords: ["structure", "outline", "toc", "table of contents", "topic tree", "suggest from sources", "subject", "subtopic", "citation"],
    blocks: [
      {
        kind: "text",
        text: "The Structure tab is where a project's outline lives — subjects, broken into topics, broken into subtopics, each one optionally citing the source it comes from. It's the table of contents Drafts and Publish both work from.",
      },
      {
        kind: "text",
        text: "\"Suggest from sources\" asks the AI to draft an outline from your captured sources — it needs at least one source to work from, and is gated by the Free plan's usage cap. If the outline already has content, it asks you to confirm \"Replace outline?\" before overwriting it.",
      },
      {
        kind: "text",
        text: "You can also hand-edit the outline directly in the topic tree editor — add, rename, reorder or remove subjects, topics and subtopics. Every change auto-saves; there's no separate Save button.",
      },
      {
        kind: "text",
        text: "A Reviewer's Structure tab is read-only: they can see the outline but can't run \"Suggest from sources\" or edit the tree.",
      },
      {
        kind: "steps",
        steps: [
          "Add at least one source on the Input tab first.",
          "Open Structure and tap \"Suggest from sources\" for an AI-drafted outline, or build the tree by hand.",
          "Edit subjects, topics and subtopics directly in the tree — changes auto-save.",
          "Move to Drafts once the outline has the shape you want.",
        ],
      },
    ],
  },
  {
    id: "project-drafts",
    title: "Drafts — generate whole-book or per-topic content",
    featureKey: "project-drafts",
    keywords: ["drafts", "whole book", "per topic", "format", "linkedin", "x thread", "reel", "podcast", "essay", "chapter outline", "version", "compare", "diff", "status", "generate", "regenerate"],
    blocks: [
      {
        kind: "text",
        text: "Once an outline exists (built on Structure), the Drafts tab shows a Whole book / Per topic toggle.",
      },
      {
        kind: "text",
        text: "Whole book mode offers six format cards — LinkedIn post, X thread, Reel script, Podcast cold-open, Long-form essay, and Chapter outline. Picking one creates a fresh draft (version 1) in that format. \"Generate full book\" fans a full-length draft out over every topic in the outline that doesn't have one yet, as a background job with a token/cost estimate and a progress indicator — see \"Generate the whole book at once\" for the details.",
      },
      {
        kind: "text",
        text: "\"Your drafts\" lists every draft you've made, and opening one shows its version history (v1, v2, …) — tap View to read a version, or pick two to Compare and see a diff between them.",
      },
      {
        kind: "text",
        text: "Per topic mode lists every row of the outline with a status chip — Not generated, Drafted, or Validated — and, for the owner, Generate / Regenerate / Open buttons on each row. A Reviewer only sees View / Open; they can't generate.",
      },
      {
        kind: "steps",
        steps: [
          "Build an outline on Structure first.",
          "Choose Whole book or Per topic on the Drafts tab.",
          "Whole book: pick a format card to draft it, or Generate full book to draft every outline topic at once.",
          "Per topic: Generate (or Regenerate) each topic row, then Open to read it.",
        ],
      },
    ],
  },
  {
    id: "project-publish",
    title: "Publish — export and share validated work",
    featureKey: "project-publish",
    keywords: ["publish", "export", "download", "epub", "pdf", "word", "docx", "add to library", "copy", "markdown", "validated", "free", "pro", "upgrade", "provenance"],
    blocks: [
      {
        kind: "text",
        text: "The Publish tab is where a validated version leaves the project. It has the same Whole book / Per topic toggle as Drafts, and only shows validated content — what you publish is the version an expert stood behind. This is the project's own Publish tab, not the app's separate Publish (Posts) nav tab, which turns any of your writing into social posts, image cards, carousels and animated cards — see \"Share & short-form\" for that.",
      },
      {
        kind: "text",
        text: "For long-form assets (book, essay, guide), you get Add to Library (compiles it into an EPUB in your reader), Download EPUB, Download PDF, and — on a Pro plan — Download Word (.docx).",
      },
      {
        kind: "text",
        text: "For social assets (LinkedIn post, X thread, Reel script, Podcast cold-open), there's no compiled file — you get Copy and Copy as Markdown instead.",
      },
      {
        kind: "text",
        text: "In Per topic mode, \"Publish book\" assembles every validated topic draft into one book export (Add to Library / EPUB / PDF / Word) — it's gated until ALL topics in the outline are validated.",
      },
      {
        kind: "text",
        text: "Free plans can read everything here but see \"Upgrade to Pro to download\" instead of the download buttons. Validated content also carries a provenance chip — \"expert-validated\" or \"operator-recorded\" — so anyone reading the exported work can see how it was validated.",
      },
    ],
  },
];
