#!/bin/bash
# Setup local staging environment for Phase 4+ testing before deploying to prod VPS

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

echo "════════════════════════════════════════════════════════════════════════════"
echo "Mentible Local Staging Setup"
echo "════════════════════════════════════════════════════════════════════════════"

# Check prerequisites
echo ""
echo "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { echo "❌ Docker not found"; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo "❌ Docker Compose not found"; exit 1; }
echo "✅ Docker + Compose available"

# Check if .env.staging exists
if [ ! -f .env.staging ]; then
    echo ""
    echo "Creating .env.staging from template..."
    cp .env.staging.template .env.staging
    echo "✅ Created .env.staging"
    echo ""
    echo "⚠️  Edit .env.staging and set required values:"
    echo "   - BYOK_MASTER_KEY (required: openssl rand -hex 32)"
    echo "   - SYSTEM_OWNER_SECRET (required: openssl rand -hex 32)"
    echo "   - DATABASE_URL (required: psql connection string)"
    echo "   - OIDC_ISSUER (optional: leave empty for anonymous demo)"
    echo ""
    read -p "Press enter when ready to continue..."
fi

# Generate keys if missing
if grep -q "^BYOK_MASTER_KEY=$" .env.staging; then
    echo "Generating BYOK_MASTER_KEY..."
    KEY=$(openssl rand -hex 32)
    sed -i.bak "s/^BYOK_MASTER_KEY=.*/BYOK_MASTER_KEY=$KEY/" .env.staging
    echo "✅ Generated BYOK_MASTER_KEY"
fi

if grep -q "^SYSTEM_OWNER_SECRET=$" .env.staging; then
    echo "Generating SYSTEM_OWNER_SECRET..."
    SECRET=$(openssl rand -hex 32)
    sed -i.bak "s/^SYSTEM_OWNER_SECRET=.*/SYSTEM_OWNER_SECRET=$SECRET/" .env.staging
    echo "✅ Generated SYSTEM_OWNER_SECRET"
fi

# Validate DATABASE_URL
if grep -q "^DATABASE_URL=$" .env.staging; then
    echo ""
    echo "❌ DATABASE_URL is required. Edit .env.staging and set it."
    echo ""
    echo "Examples:"
    echo "  • Local PostgreSQL: postgresql://postgres:postgres@localhost:5432/mentible_staging"
    echo "  • Docker postgres: postgresql://postgres:postgres@staging-db:5432/mentible_staging"
    echo ""
    exit 1
fi
echo "✅ DATABASE_URL configured"

# Build + start staging stack
echo ""
echo "Starting staging stack on port 8093..."
docker compose -f docker-compose.staging.yml --env-file .env.staging up -d --build --remove-orphans

# Wait for API to be healthy
echo ""
echo "Waiting for API to be healthy..."
for i in {1..30}; do
    if curl -s http://127.0.0.1:8093/healthz > /dev/null 2>&1; then
        echo "✅ API is healthy"
        break
    fi
    echo "  Attempt $i/30..."
    sleep 2
done

# Run migrations
echo ""
echo "Running database migrations..."
docker compose -f docker-compose.staging.yml --env-file .env.staging run --rm api \
    alembic -c /app/backend/alembic.ini upgrade head

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "✅ Staging environment ready!"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "API endpoint:       http://127.0.0.1:8093"
echo "Compose project:    docker-compose.staging.yml"
echo ""
echo "Useful commands:"
echo "  • View logs:      docker compose -f docker-compose.staging.yml logs -f api"
echo "  • Stop:           docker compose -f docker-compose.staging.yml down"
echo "  • Restart:        docker compose -f docker-compose.staging.yml restart api"
echo "  • Shell in API:   docker compose -f docker-compose.staging.yml exec api bash"
echo ""
echo "Next: Test Phase 4 flow (publish → search → import → admin takedown)"
echo ""
